server:
  port: 8080

spring:
  application:
    name: gateway
  
  cloud:
    gateway:
      # Disable discovery locator - we use explicit route definitions
      discovery:
        locator:
          enabled: false
      
      # Global CORS configuration (optional, adjust as needed)
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # Keycloak issuer URI for JWT validation (must match BFF realm)
          issuer-uri: ${SO_KEYCLOAK_ISSUER:http://localhost:8585/realms/smartorder-bff}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${SO_EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# Logging Configuration
logging:
  level:
    root: INFO
    com.smartorder.gateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

