spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SO_KEYCLOAK_ISSUER:http://localhost:8585/realms/smartorder}
  application:
    name: notification-service
  cloud:
    function:
      definition: paymentSucceeded;paymentFailed
    stream:
      kafka:
        binder:
          brokers: ${SO_KAFKA_BROKERS:localhost:29092}
        bindings:
          paymentSucceeded-in-0:
            consumer:
              enableDlq: true
          paymentFailed-in-0:
            consumer:
              enableDlq: true
      bindings:
        paymentSucceeded-in-0:
          destination: payment.succeeded
          group: notification-svc
          contentType: application/json
          consumer:
            maxAttempts: 3
        paymentFailed-in-0:
          destination: payment.failed
          group: notification-svc
          contentType: application/json
          consumer:
            maxAttempts: 3
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info
eureka:
  client:
    service-url:
      defaultZone: ${SO_EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.stream: INFO
