apiVersion: v1
kind: ConfigMap
metadata:
  name: smartorder-config
  namespace: smartorder
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SO_CONFIG_URI: "http://config-server-internal:8888"
  SO_KAFKA_BROKERS: "kafka:9092"
  SO_KEYCLOAK_ISSUER: "http://keycloak:8585/realms/smartorder-bff"
  SO_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
