spring:
  application:
    name: bff
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/smartorder-bff
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: bff-web
            client-secret: 2RTvc4QRG2P7GJf7q0lnPchOqhx9Bq19
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: ${SO_EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web.reactive.function.client: INFO
