spring:
  config:
    import: "configserver:${SO_CONFIG_URI:http://localhost:8888}"
  application:
    name: discovery-server
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
