spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${SO_CONFIG_GIT_URI:https://github.com/halitkalayci/java-advanced-project3.git}
          default-label: ${SO_CONFIG_GIT_BRANCH:main}
          search-paths:
            - backend/configs
            - backend/configs/{application}
          clone-on-start: true
          force-pull: true
        native:
          search-locations: []

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info,env