spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${SO_CONFIG_GIT_URI:https://github.com/halitkalayci/java-advanced-project3.git}
          default-label: ${SO_CONFIG_GIT_BRANCH:main}
          search-paths:
            - backend/configs
            - backend/configs/{application}
          clone-on-start: true
          force-pull: true
        native:
          search-locations: []

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${SO_EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true